version: "3"
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website
    ports:
      - 3000:3000
    volumes:
      # This bind mount allows changes on the host file system to affect the container.
      # Saving a code file can cause an incremental build, a hot reload in the browser,
      # and a reconnection of the debugger.
      # The mount is in delegated mode:
      # Changes on the host, like saving a code file, immediately affect the container.
      # Changes within the container, like build output, make their way back to the host,
      # but are not strictly synchronized.
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: yarn run start

  storybook:
    build:
      context: .
    volumes:
      - .:/usr/src/app:delegated
    ports:
      - 6006:6006
    command: yarn run storybook

networks:
  default:
    name: nateekulnetwork
